name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js (recommended)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: payments/package-lock.json

      # Install dependencies and run tests
      - name: Install & Test (Auth Service)
        working-directory: payments
        run: |
          npm install
          npm run test:ci
